### ISSUE TITLE
Add "pytest" command under test commands

### ISSUE THREAD

**Issue by bobleesj** [conda-forge/bg-mpl-stylesheets-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In PyPI v0.4.1, no test files are provided. `pytest` is not executed. In release 0.4.2 with the cookiecutter, modify `meta.yaml`

from:

```
  commands:
    - pip check
    - pip list
```

to

```
  commands:
    - pip check
    - pip list
    - pytest
```

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by bobleesj** [comment]
Conda-forge CI uses Python 3.13.

Full tests via pytest will be added in v0.5.0

**Comment by sbillinge** [comment]
because of the 3.13 issues let's not push this out to conda-forge but do the `0.5.0` release and push that out.
